import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from 'next/styles/Home.module.css'

import { useRouter } from 'next/router';

import MainButton from '../components/mainButton';


const inter = Inter({ subsets: ['latin'] })

//This is the homepage for users once they log in to Nutriget
export default function Home() {
  const router = useRouter();
  const query = router.query; //This will be 'true' if the user just logged in
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <h1>
            Nutriget
          </h1>
        </div>
        {query.login ? (<p>Welcome back, user!</p>) : (<h1></h1>)}

        <Link
          href={`/new`}
          className={styles.bigButton}
          rel="noopener noreferrer">
          <div>
            <h1 className={inter.className}>
                New
            </h1>

            <p className={inter.className}>
                Add a new meal
            </p>
          </div>    
          
          <Image width={175} height={175} src='/add_sign.png'></Image>
        </Link>

        <div className={styles.grid}>
          {/*This is a grid rather than flexbox. Think like cubby-hole*/}
        
            
          <MainButton 
            page="today" 
            title="Today's Calories" 
            description="Check if you're a fatty. 🍔🍟🥞"/>
          
          <MainButton
            page="history"
            title="Meal History"
            description="View your past meals"/>
          
          
          

         </div>
      </main>
    </>
  )
}
