import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from 'next/styles/Home.module.css'

import { useRouter } from 'next/router';


const inter = Inter({ subsets: ['latin'] })

//This is the homepage for users once they log in to Nutriget
export default function Home() {
  const router = useRouter();
  const query = router.query; //This will be 'true' if the user just logged in
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <h1>
            Nutriget
          </h1>
        </div>
        {query.login ? (
        <p>Welcome back, user!</p>) : (<h1>Shush</h1>)}

        <div className={styles.grid}> {/*This is a grid rather than flexbox. Think like cubby-hole*/}
          <Link
            href="/today"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Today's Calories <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Check if you're a fatty.
              🍔🍟🥞
            </p>
          </Link>
          <Link
            href="/today"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
               <span>Meal History-&gt;</span>
            </h2>
            <p className={inter.className}>
              
              View your past meals
            </p>
          </Link>
          

         </div>
      </main>
    </>
  )
}
