import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from 'next/styles/Home.module.css'
import login from 'next/styles/Login.module.css'

import {useState} from 'react';
import { useRouter } from 'next/router'


const inter = Inter({ subsets: ['latin'] })

//This is the login page for unauthenticated users
export default function Login() {
  const router = useRouter();
  const [formData, setFormdata] = useState({email: '', password:''})

  //This changes the 
  const handleChange = (event) => {
    setFormdata({ ...formData, [event.target.name]: event.target.value });
  }

  const handleSubmit = async (event) => {
    event.preventDefault();
    const result = await fetch ('/api/login', {
      method: 'POST',
      body: JSON.stringify(formData),
      headers: { 'Content-Type': 'application/json'},
    });
    const data = await result.json();

    if (data.response == "You're In!") {
      router.push({
        pathname: '/',
        query: {login: true},
      })
    }
  }
  
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.title}>
          <h1>
            Welcome Back
          </h1>
        </div>

        <form onSubmit={handleSubmit} className={login.form}>
            <input className={login.input}
            name="email"
            placeholder="Email"
            onChange={handleChange}
            />
            <input className={login.input}
            name="password"
            placeholder="Password"
            onChange={handleChange}
            />
            <button type="submit" className={login.submit}>
                Log in
            </button>

        </form>
      </main>
    </>
  )
}
