//SETUP THE DATABASE FOR NEW TASKS.
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from 'next/styles/Home.module.css'
import login from 'next/styles/Login.module.css'

import {useState, useEffect} from 'react';
import { useRouter } from 'next/router'
import ReactModal from 'react-modal';
import MainButton from 'next/components/mainButton'

const inter = Inter({ subsets: ['latin'] })


export default function New() {

   
    const [modalOpen, setModalOpen] = useState(false);

    const openModal = () => {
    setModalOpen(true);
    };

    const closeModal = () => {
    setModalOpen(false);
    };

  return (
     <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
            <button className={styles.bigButton} onClick={openModal}></button>
            <ReactModal isOpen={modalOpen} 
            onRequestClose={closeModal}
            onAfterOpen={console.log("Bigmanting")}>
            {/* Modal content goes here */}
            <MainButton
            page={'scratch'}
            title={'Start From Scratch'}
            description={'Tell us what your meal is'}/>

            <MainButton
            page={'history'}
            title={'Add From History'}
            description={'Having the same meal again?'}/>
            </ReactModal>
      </main>

    </>
    
  );
};

