import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from 'next/styles/Home.module.css'
import login from 'next/styles/Login.module.css'

import {useState} from 'react';
import { useRouter } from 'next/router'
import { getSession } from "/session";
import { setSession } from "/session";
import { useEffect } from 'react';



const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps({ req, res }) {
    const { user } = getSession(req) ?? { user: null};
    console.log(JSON.stringify(user))
    if (!user) return { redirect: { permanent: false, destination: "/login" } };
    else return { props: { user } };
  }

//This is the Register page for unregistered users
export default function Onboard({ user }) {
    const router = useRouter();
    const [formData, setFormdata] = useState({calories: 0, protein: 0})
    //IF this user is already onboarded, redirect them to the home page

    useEffect(() => {
        if (!user.onboardNeeded) {
            router.push('/')
        }
    }, [user, router]);

    //This this changes the formData state when the user changes any of the input fields
    const handleChange = (event) => {
        setFormdata({ ...formData, [event.target.name]: event.target.value }); 
        console.log(formData)
    }



    const setCalories = (e) => {
        e.preventDefault();
        fetch('/api/onboard', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(formData),
        })
          .then((res) => res.json())
          .then((json) => {
            if (json.user) {
                router.push('/');
            }
          });
      }

  return (
    <>
      <Head>
        <title>Onboarding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>
            <h1>Welcome to Nutriget</h1>
        </div>
        <div className={styles.title}>
            <h4>Lets get you started</h4>
        </div>
        <form onSubmit={setCalories}>
        <div className={styles.body}>What is your daily calorie budget? <br></br>
            <input  onChange={handleChange} placeholder="e.g 2000" type="number" id="calories" name="calories" min="0" max="5000"></input>
        </div>
        <div className={styles.body}>What is your daily protein goal? <br></br>
            <input  onChange={handleChange} placeholder="e.g 150g" type="number" id="protein" name="protein" min="0" max="1000"></input>
        </div>
        <br></br>
        <button type="submit">Submit</button>
        </form>
      </main>
    </>
  )
}
