import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from 'next/styles/Home.module.css'
import login from 'next/styles/Login.module.css'

import {useState, useEffect} from 'react';
import { useRouter } from 'next/router'



const inter = Inter({ subsets: ['latin'] })

//This is the Register page for unregistered users
export default function Register() {
  const router = useRouter();
  const [formData, setFormdata] = useState({username: '',email: '', password:'', from: 'register'})
  const [response_message, setResponse] = useState('')
  const[buttonDisabled, setButtonDisabled] = useState(true); //This is the state of the button. It is disabled by default. It is enabled when the user enters all the required fields
  const [Hovering, setHovering] = useState(false);

  const handleMouseEnter = () => setHovering(true);
  const handleMouseLeave = () => setHovering(false);

  

  async function isGood (formData) {
    //Check if all the formData are OK. Only then should the func return True. Otherwise return False. 

    const result = await fetch ('/api/checkForm', {
      method: 'POST',
      body: JSON.stringify(formData),
      headers: {'Content-Type' : 'application/json'}
    }); 
    const data = await result.json();
    if (result.status == 400) {
      setResponse(data.response);

      return false;
  }
  else {
    setResponse('');
    setButtonDisabled(false);
    return true;
  }
}

  //This this changes the formData state when the user changes any of the input fields
  
  const handleChange = (event) => {
    setFormdata({ ...formData, [event.target.name]: event.target.value }); 
  };
  //Check the form whenever the formData changes
  useEffect(() => {
    isGood(formData);
  }, [formData]);


  //This is the function that is called when the user submits the form
  const handleSubmit = async (event) => {

    event.preventDefault(); //Prevent the page from reloading
    const result = await fetch ('/api/register', {
      method: 'POST',
      body: JSON.stringify(formData),
      headers: { 'Content-Type': 'application/json'}
    });
    
    const data = await result.json();

    if (data.response) {
      //TODO: Change the below to a redirect to the onboarding page
      router.push('/login');
    }
    else {
      alert("Fix the details fam")
    }
  }
  
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       
        <div className={styles.title}>
          <h1>
            Join Nutriget
          </h1>
        </div>

       
        <form onSubmit={handleSubmit} className={login.form}>

            <input className={login.input} //Username input
            name="username"
            placeholder="Username"
            onChange={handleChange}
            />

            <input className={login.input} //Email input
            name="email"
            placeholder="Email"
            onChange={handleChange}
            />

            <input className={login.input} //Password input
            name="password"
            placeholder="Password"
            onChange={handleChange}
            />

            <div className={login.buttonContainer}> 
              <button onMouseEnter={handleMouseEnter} onMouseLeave={handleMouseLeave} 
              type="submit" className={login.submit}>
                  Register
              </button>
              <span className={`${login.error} ${Hovering ? login.error.visible : login.error.hidden}`}>
                {response_message}
              </span>              
            </div>
        </form>
      </main>
    </>
  )
}
