//SETUP THE DATABASE FOR NEW TASKS.
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from 'next/styles/Home.module.css'
import login from 'next/styles/Login.module.css'

import {useState, useEffect} from 'react';
import { useRouter } from 'next/router'
import ReactModal from 'react-modal';
import MainButton from 'next/components/mainButton'
import ingredients from '../components/ingredients';
import Ingredients from '../components/ingredients'



const inter = Inter({ subsets: ['latin'] })



export default function New() {

    //Request URL https://api.edamam.com/api/nutrition-details?app_id=f93901b3&app_key=250416ac1f75a3a9d6a2bdd2c501c0ef&beta=false&force=false

    const [foodInput, setFood] = useState();
    const [calories, setCalories] = useState(0);
    const [data, setData] = useState([]);


    //Accessing the edamam API with a POST request
    const handleSubmit = async (event) => {

      event.preventDefault(); //Prevent the page from reloading
      const result = await fetch ('/api/getNutrition  ', {
        method: 'POST',
        body: JSON.stringify(foodInput),
        headers: { 'Content-Type': 'application/json'}
      });      
      
      const response = await result.json();
      setData(response.data);
    }
    

  return (
     <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form>
          <input type="text" placeholder="Enter Food" onChange={(e) => setFood(e.target.value)}></input>
          <button type ='submit' onClick={handleSubmit}>Submit Food</button>
        </form>
        {data.length > 0 && <Ingredients data={data}/>}
        <h1>
          That is mental
        </h1>
        
        
      </main>

    </>
    
  );
};

