//SETUP THE DATABASE FOR NEW TASKS.
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from 'next/styles/Home.module.css'
import login from 'next/styles/Login.module.css'

import {useState, useEffect} from 'react';
import { useRouter } from 'next/router'
import ReactModal from 'react-modal';
import MainButton from 'next/components/mainButton'

const inter = Inter({ subsets: ['latin'] })


export default function New() {

    //Request URL https://api.edamam.com/api/nutrition-details?app_id=f93901b3&app_key=250416ac1f75a3a9d6a2bdd2c501c0ef&beta=false&force=false

    const [modalOpen, setModalOpen] = useState(false);
    const [food, setFood] = useState();
    const [calories, setCalories] = useState();

    //Functions that open and close the modal component
    const openModal = () => {
    setModalOpen(true);
    };
    const closeModal = () => {
    setModalOpen(false);
    };

    //Accessing the edamam API with a POST request
    const handleSubmit = async (event) => {

      event.preventDefault(); //Prevent the page from reloading
      const result = await fetch ('https://api.edamam.com/api/nutrition-details?app_id=f93901b3&app_key=250416ac1f75a3a9d6a2bdd2c501c0ef&beta=false&force=false', {
        method: 'POST',
        body: JSON.stringify(food),
        headers: { 'Content-Type': 'application/json'}
      });
      
      const data = await result.json();
      setCalories(data.calories);

  
      console.log(data);
    }
    

  return (
     <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form>
          <input type="text" placeholder="Enter Food" onChange={(e) => setFood({'title': 'meal', 'ingr' : [e.target.value]})}></input>
          <button type ='submit' onClick={handleSubmit}>Submit Food</button>
        </form>
        <h1>
          That is {calories} calories
        </h1>
        
        
      </main>

    </>
    
  );
};

