import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useEffect } from 'react';
import Link from 'next/link'

import { Inter } from 'next/font/google'
import styles from 'next/styles/Home.module.css'
import CircularProgress from 'next/components/circular'
import { getSession } from "/session";

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps({ req, res }) {
  const { user } = getSession(req) ?? { user: null};
  if (!user) return { redirect: { permanent: false, destination: "/login" } };
  else return { props: { user } };
}

export default function Today( { user } ) {
  
    //Setting the state of calories, so now setCalories updates the calories variable
    const [calories, setCalories] = useState(0);
    const [calorieLimit, setCalorieLimit] = useState(1);

    //Function to convert calories to percentage of max
    const toPercent = (value) => Math.round(value*100/calorieLimit);

    //TODO: Getting this user's daily limit (first gotta do onboarding)
    const getCalorieLimit = () => {
      fetch ('/api/getCalories', {
      method: 'GET',
      headers: {'Content-Type': 'application/json'},
    })

    .then(response => response.json())
    .then(calorie_data => {
        if (calorie_data.response == 'No calorie limit set') {
          //TODO: make this more streamlined for the user (like bringing the settings modal from index.js to here)
          return <Link href='/'>go to settings and set ur calorie limit</Link>
        }
        else {
          //Setting the state of calories, so now setCalories updates the calories variable
          setCalorieLimit(calorie_data.calorieLimit);
          return calorie_data.calorieLimit;
        }
    });
  }
    //Getting this user's meals for today
    const getTodayMeals = () => {
      fetch ('/api/today', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({user_id: user.id})
    })
    .then(response => response.json())
    .then(meal_data => {
        if (meal_data.response == 'No meals') {
        }
        else {
            const limit = getCalorieLimit();
            //Calculating the total calories, updating state
            let counter_calories = 0;
            for (let i = 0; i < meal_data.rows.length; i++) {
              counter_calories += meal_data.rows[i].calories;
              setCalories(counter_calories); 
            }

            //Updating the angle of the progress circle, using updated calorie values
            console.log("CALORIES " + counter_calories)
            const angle = toPercent(counter_calories)*3.6;
            console.log("HEHEHE" + angle)
        
            //Updating the progress circle
            let new_background = `conic-gradient(#44ff44 ${angle}deg, #888888 0deg)`;

            const element = document.getElementById("circle");
            element.style.background = new_background;
                
            } 
    });
  }
    useEffect(() => {
        getTodayMeals(); 
    }, []);

    
    function Fatty(){
      if (calories > calorieLimit){
        return (
          <div className="comment">You&apos;ve eaten more than enough fatty</div>
        );
      }
      else{
        return(
          <div className="comment">You&apos;ve got {Math.round(calorieLimit-calories)} calories ({100-toPercent(calories)}%) left to go</div>
        )
      }
    }

  return (
    <>
      <Head>
        <title>Today&apos;s Calories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.center}>
          <h1 className={inter.className}>
            Today&apos;s Calories
          </h1>
        </div>
         
        <div className={styles.center}>

          <CircularProgress percentage={toPercent(calories)} />
          <Fatty></Fatty>
        </div>
         <button></button>
      
    </>
  )
}
