import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { Inter } from 'next/font/google';
import styles from 'next/styles/Home.module.css';
import login from 'next/styles/Login.module.css';

import {React, useState, useEffect} from 'react';
import { useRouter } from 'next/router';



export default function Verify(email) {

    return (
        <>
        <Head>
          <title>Register</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
         
          <div className={styles.title}>
            <h1>
              One more step, verify your email
            </h1>
          </div>
        </main>
      </> 
    )
}